### ISSUE TITLE
E: Package 'php5-mysql' has no installation candidate

### ISSUE THREAD

**Issue by X4mp** [fuhrysteve/php-docker-apache-example#2]
executing `docker build -t php-docker-demo .` stops when installing php5-mysql with the following error:

> Package php5-mysql is a virtual package provided by:
  php5-mysqlnd 5.6.33+dfsg-0+deb8u1 [Not candidate version]
  php5-mysqlnd 5.6.30+dfsg-0+deb8u1 [Not candidate version]

> E: Package 'php5-mysql' has no installation candidate
> The command '/bin/sh -c apt-get update &&     apt-get install -y php5-mysql &&     apt-get clean' returned a non-zero code: 100

**Comment by pgrunm** [comment]
Hey @X4mp ,

I got exactly the same issue when trying to build the container. As mentioned in [PHP Docker documentation](https://hub.docker.com/_/php/) we're not required to install the  `php5-mysql` package.

I was able to build the container with this dockerfile.

```Dockerfile
FROM php:7.0-apache 
COPY myapp /var/www/html/ 
```

**Comment by X4mp** [comment]
Sorry for the late answer. Sounds like a reasonable fix.
